// Copyright (c) Microsoft Corporation
// The Microsoft Corporation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Text.Json.Serialization;

namespace Microsoft.PowerToys.Settings.UI.Library;

/// <summary>
/// A single "keep awake for" entry shown in the Awake tray icon menu. The Settings UI edits a list of
/// these and persists them as the <see cref="AwakeProperties.CustomTrayTimes"/> dictionary (label to seconds).
/// </summary>
public partial class AwakeTrayInterval : INotifyPropertyChanged
{
    public const uint MaxHours = 999;
    public const uint MaxMinutes = 59;

    private uint _hours;
    private uint _minutes;
    private string _label = string.Empty;

    public event PropertyChangedEventHandler PropertyChanged;

    public AwakeTrayInterval()
    {
    }

    public AwakeTrayInterval(uint hours, uint minutes)
    {
        _hours = hours;
        _minutes = minutes;
    }

    /// <summary>
    /// Creates an interval from a total number of seconds, rounding partial minutes up so that a
    /// hand-edited value such as 90 seconds is never silently dropped to zero.
    /// </summary>
    public static AwakeTrayInterval FromSeconds(uint totalSeconds)
    {
        uint totalMinutes = (totalSeconds + 59) / 60;
        return new AwakeTrayInterval(totalMinutes / 60, totalMinutes % 60);
    }

    [JsonPropertyName("hours")]
    public uint Hours
    {
        get => _hours;
        set
        {
            if (SetProperty(ref _hours, value))
            {
                OnPropertyChanged(nameof(TotalSeconds));
            }
        }
    }

    [JsonPropertyName("minutes")]
    public uint Minutes
    {
        get => _minutes;
        set
        {
            if (SetProperty(ref _minutes, value))
            {
                OnPropertyChanged(nameof(TotalSeconds));
            }
        }
    }

    /// <summary>
    /// Gets or sets the text shown in the tray menu for this interval. Generated by the view model from
    /// <see cref="Hours"/> and <see cref="Minutes"/>; not persisted on its own.
    /// </summary>
    [JsonIgnore]
    public string Label
    {
        get => _label;
        set => SetProperty(ref _label, value ?? string.Empty);
    }

    [JsonIgnore]
    public uint TotalSeconds => (_hours * 3600) + (_minutes * 60);

    private bool SetProperty<T>(ref T field, T value, [CallerMemberName] string propertyName = null)
    {
        if (EqualityComparer<T>.Default.Equals(field, value))
        {
            return false;
        }

        field = value;
        OnPropertyChanged(propertyName);
        return true;
    }

    private void OnPropertyChanged(string propertyName)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
